# Generated by Django 4.1.3 on 2022-11-03 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('height', models.CharField(max_length=20)),
                ('mass', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('homeworld', models.TextField()),
                ('films', models.TextField()),
                ('species', models.TextField()),
            ],
        ),
    ]
