# Generated by Django 4.1.3 on 2022-11-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('episode_id', models.CharField(max_length=10)),
                ('opening_crawl', models.TextField()),
                ('director', models.CharField(max_length=100)),
                ('producer', models.CharField(max_length=100)),
                ('planets', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Planets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('rotation_period', models.CharField(max_length=30, null=True)),
                ('orbital_period', models.CharField(max_length=30, null=True)),
                ('diameter', models.CharField(max_length=30, null=True)),
                ('climate', models.CharField(max_length=30, null=True)),
                ('gravity', models.CharField(max_length=30, null=True)),
                ('terrain', models.CharField(max_length=200, null=True)),
                ('surface_water', models.CharField(max_length=30, null=True)),
                ('population', models.CharField(max_length=30, null=True)),
                ('residents', models.CharField(max_length=30, null=True)),
                ('films', models.TextField()),
            ],
        ),
    ]
